//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodFunday
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutUs
    {
        public string title { get; set; }
        public string summary { get; set; }
        public string decription { get; set; }
        public string mainImage { get; set; }
        public Nullable<bool> isSauce { get; set; }
        public string sauceImage { get; set; }
    }
}
