//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodFunday
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Avartar { get; set; }
        public string Achievements { get; set; }
        public string linkFb { get; set; }
        public string linkTw { get; set; }
        public string linkIn { get; set; }
    }
}
